# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_app.Book')),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='bookcontent',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_app.Note'),
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.ManyToManyField(through='notes_app.BookContent', to='notes_app.Note'),
        ),
    ]
