# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-22 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_auto_20170522_2235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcontent',
            unique_together=set([('note', 'book')]),
        ),
    ]
