# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-24 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20170522_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('time', models.DateTimeField()),
                ('is_new', models.NullBooleanField()),
            ],
        ),
    ]
