# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_requeststat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_content', to='notes_app.Book'),
        ),
        migrations.AlterField(
            model_name='bookcontent',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_content', to='notes_app.Note'),
        ),
    ]
