# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_auto_20170525_0708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestStat',
        ),
    ]
