# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0007_delete_requeststat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='note',
        ),
        migrations.AlterUniqueTogether(
            name='bookcontent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bookcontent',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcontent',
            name='note',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookContent',
        ),
    ]
