# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_auto_20170616_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='photo',
        ),
    ]
