# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0009_remove_note_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
